aaa_osslo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from entries import views as views_entries
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('django.conf.urls.i18n')),
    path('', views_entries.index, name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls"), name='accounts'),
    path("entries/", include("entries.urls"), name='entries'),
]

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'accounts'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('change_password/', views.change_password, name='change_password'),
    path('toggle_current_language/<slug:next_view>/', views.toggle_current_language, name='toggle_current_language'),
    path('toggle_translation_direction/', views.toggle_translation_direction, name='toggle_translation_direction'),
    path('set_current_language/<int:lang_id>', views.set_current_language, name='set_current_language'),
] 

urlpatterns += staticfiles_urlpatterns()

entries/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'entries'

urlpatterns = [
    path('', views.index, name='index'),
    path('my_languages/', views.my_languages, name='my_languages'),
    path('add_language/', views.add_language, name='add_language'),
    path('edit_language/<int:lang_id>/', views.edit_language, name='edit_language'),
    path('delete_language/', views.delete_language, name='delete_language'),
    path('edit_articles/<int:lang_id>/', views.edit_articles, name='edit_articles'), # if you change edit_articles here, make the change also in the delete_article view
    path('add_articles/<int:lang_id>/', views.add_articles, name='add_articles'),
    path('delete_article/', views.delete_article, name='delete_article'),
    path('edit_topics/<int:lang_id>/', views.edit_topics, name='edit_topics'), 
    path('add_topics/<int:lang_id>/', views.add_topics, name='add_topics'),
    path('delete_topic/', views.delete_topic, name='delete_topic'),
    path('add_entry/', views.add_entry, name='add_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/', views.delete_entry, name='delete_entry'),
    path('edit_translations/<int:entry_id>', views.edit_translations, name='edit_translations'),
    path('delete_translation/', views.delete_translation, name='delete_translation'),
    path('add_translation/<int:entry_id>', views.add_translation, name='add_translation'),
    
]

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from entries.models import Language

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  current_language = models.ForeignKey(Language, null=True, blank=True, on_delete=models.SET_NULL)
  translate_by_home_lang = models.BooleanField(default=False)

  def __str__(self):
    return f"{self.user.username}/{self.current_language}"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _

class RegistrationForm(UserCreationForm):
  username = forms.CharField(widget=forms.TextInput(
    attrs={'placeholder': _('username'), 'title': _('username'), 'autocomplete': 'off'}))
  password1 = forms.CharField(widget=forms.PasswordInput(
    attrs={'placeholder': _('password'), 'title': _('password')}))
  password2 = forms.CharField(widget=forms.PasswordInput(
    attrs={'placeholder': _('confirm password'), 'title': _('confirm password')}))

  class Meta:
    model = User
    fields = ['username', 'password1', 'password2',]

class LoginForm(AuthenticationForm):
  username = forms.CharField(widget=forms.TextInput(
    attrs={'placeholder': _('username'), 'title': _('username'), 'autocomplete': 'off'}))
  password = forms.CharField(widget=forms.PasswordInput(
    attrs={'placeholder': _('password'), 'title': _('password')}))

  class Meta:
    model = User
    fields = ['username', 'password']

class PasswordForm(PasswordChangeForm):
  old_password = forms.CharField(widget=forms.PasswordInput(
    attrs={'placeholder': _('old password'), 'title': _('old password'), 'autocomplete': 'off'}))
  new_password1 = forms.CharField(widget=forms.PasswordInput(
    attrs={'placeholder': _('new password'), 'title': _('new password')}))
  new_password2 = forms.CharField(widget=forms.PasswordInput(
    attrs={'placeholder': _('confirm new password'), 'title': _('confirm new password')}))

  class Meta:
    model = User
    fields = ['old_password', 'new_password1', 'new_password2',]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, LoginForm, PasswordForm
from .models import Profile
from entries.models import Language
from entries.views import index as entries_index, add_entry as entries_add_entry
from django.utils.translation import gettext_lazy as _


@login_required
def settings(request):
  return render (request, 'accounts/settings.html')

def register(request):
  if request.method == 'POST':
    form = RegistrationForm(request.POST)
    if form.is_valid():
      user = form.save()
      Profile.objects.create(user=user)
      login(request, user)
      return redirect('entries:my_languages')
  else:
    form = RegistrationForm()
  context = {'form': form}
  return render(request, 'accounts/register.html', context)

def login_view(request):
  if request.method == 'POST':
    form = LoginForm(data=request.POST)
    if form.is_valid():
      user = form.get_user()
      login(request, user)

      if 'next' in request.POST:
        return redirect(request.POST.get('next'))
      if not request.user.profile.current_language:
        # user with no languages cannot be redirected to the dictionary section
        return redirect('entries:my_languages')
      return redirect('entries:index')
  else:
    form = LoginForm()
  context = {'form': form}
  return render(request, 'accounts/login.html', context)

@login_required
def logout_view(request):
  logout(request)
  return redirect('accounts:login')

@login_required
def change_password(request):
  if request.method == 'POST':
    form = PasswordForm(request.user, request.POST)
    if form.is_valid():
      user = form.save()
      update_session_auth_hash(request, user)
      return render(request, 'accounts/change_password.html', {'message': _('Your password has been changed.')})
  else:
    form = PasswordForm(request.user)
  context = {'form': form}
  return render(request, 'accounts/change_password.html', context)

@login_required
def delete_user(request):
  # custom_error and form_valid are a hack to make sure that only the current user 
  # can be deleted (no cross-account deletion) while there is no way of hinting that 
  # you guessed the credentials of some other user

  custom_error = False
  if request.method == 'GET':
    form = LoginForm()
  else:
    form = LoginForm(data=request.POST)
    form_valid = form.is_valid()
    if request.user.username != request.POST.get('username'):
      form_valid = False
      custom_error = True
    if form_valid:
      user = form.get_user()
      user.delete()
      request.user = None
      request.method = 'GET'
      return login_view(request)

  return render(request, 'accounts/delete_user.html', {'form': form, 'custom_error': custom_error})

@login_required
def toggle_current_language(request, next_view):

  if Language.objects.filter(user=request.user).exists():

    languages = []
    for language in Language.objects.filter(user=request.user).order_by('id'):
      languages.append(language)
    curr_lang = request.user.profile.current_language
    curr_index = languages.index(curr_lang)

    curr_index += 1
    if curr_index == len(languages):
      curr_index = 0

    request.user.profile.current_language = languages[curr_index]
    request.user.profile.save()  

  if next_view == 'entries':
    return entries_index(request)
  if next_view == 'add_entry':
    return entries_add_entry(request)
  return HttpResponse(status=204)
    
@login_required
def set_current_language(request, lang_id):
  if Language.objects.filter(pk=lang_id, user=request.user).exists:
    for language in Language.objects.filter(user=request.user):
      if language.id == lang_id:
        request.user.profile.current_language = language
        request.user.profile.save()  
        return entries_add_entry(request)
  return HttpResponse('wrong language')

@login_required
def toggle_translation_direction(request):
  request.user.profile.translate_by_home_lang = not request.user.profile.translate_by_home_lang
  request.user.profile.save()
  return redirect(entries_index)

accounts/templates/accounts/accounts_index.html
{% extends 'index.html' %}
{% load static i18n %}
{% block html_lang %}{% trans 'en' %}{% endblock %}
{% block title %}{% trans 'Perdi - personal dictionary' %}{% endblock %}
{% block content %}{% endblock %}

accounts/templates/accounts/change_password.html
{% extends 'accounts/accounts_index.html' %}
{% load static i18n %}
{% block content %}

{% if message %}
{{ message }}

{% else %}

<h3 class="text-center">{% trans 'change password' %}</h3>
<form class="site-form" action="{% url 'accounts:change_password' %}" method="POST">
  {% csrf_token %}
  <p class="centered mb-0">{{ user }}</p>
  {{ form.old_password }}
  {{ form.new_password1 }}
  {{ form.new_password2 }}
  <button type="sumbit" class="btn btn-outline-info btn-block">{% trans 'change password' %}</button>
  {% if form.errors %}
  <div class="alert alert-danger">
    <p>{{ form.errors.old_password }}</p>
    <p>{{ form.errors.new_password1 }}</p>
    <p>{{ form.errors.new_password2 }}</p>
  </div>
  {% endif %}
</form>

{% endif %}
{% endblock %}

accounts/templates/accounts/delete_user.html
{% extends 'accounts/accounts_index.html' %}
{% load static i18n %}
{% block content %}

<h3 class="centered">{% trans 'delete my perdi account' %}</h3>
<p class="text-center">{% trans "To make sure it's really you, fill in your login credentials." %}</p>
<form class="site-form" action="{% url 'accounts:delete_user' %}" method="POST">
  {% csrf_token %}

  {{ form.username }}
  {{ form.password }}
  <div class="alert alert-danger">
    {% trans 'Your account will be deleted <i>permanently</i> along with all your data and content.' %}
  </div>
  <button type="submit" class="btn btn-outline-danger btn-block">{% trans 'delete account' %}</button>
  {% if form.errors or custom_error %}
  <div class="alert alert-danger">
    {% trans 'incorrect credentials' %} 
  </div>
  {% endif %}
</form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/accounts_index.html' %}
{% load static i18n %}
{% block content %}

<h3 class="centered">perdi</h3>
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {{ form.username }}
  {{ form.password }}
  <button type="submit" class="btn btn-outline-info btn-block">{% trans 'Log in' %}</button>
  <p class="text-center mt-3">{% trans 'No account yet?' %} <a href="{% url 'accounts:register' %}">{% trans 'Sign up' %}</a>.</p>
  {% if form.errors %}
  <div class="alert alert-danger">
    {{ form.errors.username }}
    {{ form.errors.password }}
    {{ form.non_field_errors }}
  </div>
  {% endif %}
</form>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/accounts_index.html' %}
{% load static i18n %}
{% block content %}

<h3 class="centered">{% trans 'register to perdi' %}</h3>
<form class="site-form" action="{% url 'accounts:register' %}" method="POST">
  {% csrf_token %}
  {{ form.username }}
  {{ form.password1 }}
  {{ form.password2 }}
  <button type="submit" class="btn btn-outline-info btn-block">{% trans 'Sign up' %}</button>
  <p class="text-center mt-3">{% trans 'Already registered?' %} <a href="{% url 'accounts:login' %}">{% trans 'Log in' %}</a>.</p>
  {% if form.errors %}
  <div class="alert alert-danger">
    {{ form.errors.username }}
    {{ form.errors.password1 }}
    {{ form.errors.password2 }}
    {{ form.non_field_errors }}
  </div>
  {% endif %}
  <p class="text-justify">{% trans 'Because we do not ask for your email address, we will not be able to reset your password should you ever forget it. In other words - if you forget your password, there is no way you can access your perdi account anymore.' %}</p>
</form>


{% endblock %}

accounts/templates/accounts/settings.html
{% extends 'accounts/accounts_index.html' %}
{% load static i18n %}
{% block content %}
  <h3>{% trans 'my account' %}</h3>

  <div class="d-flex justify-content-start align-items-center mb-2 mt-3">
    <div>{% trans 'display perdi in' %}</div>
    <div id="change-language" class="ml-2">
      {% get_current_language as display_lang %}
      {% get_available_languages as LANGUAGES %}
      {% get_language_info_list for LANGUAGES as available_languages %}
      <form class="" id="perdi-language-form" action="{% url 'set_language' %}" method="POST">
        <div class="form-row align-items-center">
          {% csrf_token %}
  
          <div>
            <select name="language" id="perdi-language-select" class="custom-select form-low py-0">
              {% for language in available_languages %}
              <option 
                value="{{ language.code }}"
                {% if language.code == display_lang %} selected="selected" {% endif %}
                >{{ language.name_local }} {{ language.code }}
              </option>
              {% endfor %}
            </select>
          </div>
          
        </div>
      </form>
    </div>
  </div>

  <div class="mb-3">
    <a href="{% url 'accounts:change_password' %}">{% trans 'change password' %}</a>
  </div>

  <div class="mb-3">
    <a href="{% url 'accounts:logout' %}" onclick="localStorage.clear();">{% trans 'log out' %}</a>
  </div>

  <div class="mb-3">
    <a class="link-danger" href="{% url 'accounts:delete_user' %}" onclick="localStorage.clear();">{% trans 'delete account' %}</a>
  </div>

  {% endblock %}