aaa_osslo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from entries import views as views_entries
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('django.conf.urls.i18n')),
    path('', views_entries.index, name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls"), name='accounts'),
    path("entries/", include("entries.urls"), name='entries'),
]

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'accounts'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('change_password/', views.change_password, name='change_password'),
    path('toggle_current_language/<slug:next_view>/', views.toggle_current_language, name='toggle_current_language'),
    path('toggle_translation_direction/', views.toggle_translation_direction, name='toggle_translation_direction'),
    path('set_current_language/<int:lang_id>', views.set_current_language, name='set_current_language'),
] 

urlpatterns += staticfiles_urlpatterns()

entries/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'entries'

urlpatterns = [
    path('', views.index, name='index'),
    path('my_languages/', views.my_languages, name='my_languages'),
    path('add_language/', views.add_language, name='add_language'),
    path('edit_language/<int:lang_id>/', views.edit_language, name='edit_language'),
    path('delete_language/', views.delete_language, name='delete_language'),
    path('edit_articles/<int:lang_id>/', views.edit_articles, name='edit_articles'), # if you change edit_articles here, make the change also in the delete_article view
    path('add_articles/<int:lang_id>/', views.add_articles, name='add_articles'),
    path('delete_article/', views.delete_article, name='delete_article'),
    path('edit_topics/<int:lang_id>/', views.edit_topics, name='edit_topics'), 
    path('add_topics/<int:lang_id>/', views.add_topics, name='add_topics'),
    path('delete_topic/', views.delete_topic, name='delete_topic'),
    path('add_entry/', views.add_entry, name='add_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/', views.delete_entry, name='delete_entry'),
    path('edit_translations/<int:entry_id>', views.edit_translations, name='edit_translations'),
    path('delete_translation/', views.delete_translation, name='delete_translation'),
    path('add_translation/<int:entry_id>', views.add_translation, name='add_translation'),
    
]

urlpatterns += staticfiles_urlpatterns()

templates/index.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="{% block html_lang %}{% endblock %}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'favicon.png' %}" />
  <!-- bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- css -->
  <link rel="stylesheet" href="{% static 'styles.css' %}">

</head>
<body class="p-2">
  {% if user.is_authenticated %}
  <div class="d-flex justify-content-around mb-2 pb-2 border-b">

    {% if user.languages.all %}
    <div>
      <span>
        <a href="{% url 'entries:index' %}" class="p-1">
          <i data-feather="book-open"></i>
        </a>
      </span>
    </div>
    {% endif %}

    <div>
      <span>
        <a href="{% url 'entries:my_languages' %}" class="p-1">
          <i data-feather="settings"></i>
        </a>
      </span>
    </div>

    <div>
      <span>
        <a href="{% url 'accounts:settings' %}" class="p-1">
          <i data-feather="user"></i>
        </a>
      </span>
    </div>

  </div>
  {% endif %}

  {% block content %}
  {% endblock %}
</body>

<!-- feather icons -->
<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
<script>feather.replace();</script>  
<!-- js -->
<script src="{% static 'index.js' %}"></script>

</html>