aaa_osslo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from entries import views as views_entries
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('django.conf.urls.i18n')),
    path('', views_entries.index, name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls"), name='accounts'),
    path("entries/", include("entries.urls"), name='entries'),
]

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'accounts'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('change_password/', views.change_password, name='change_password'),
    path('toggle_current_language/<slug:next_view>/', views.toggle_current_language, name='toggle_current_language'),
    path('toggle_translation_direction/', views.toggle_translation_direction, name='toggle_translation_direction'),
    path('set_current_language/<int:lang_id>', views.set_current_language, name='set_current_language'),
] 

urlpatterns += staticfiles_urlpatterns()

entries/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'entries'

urlpatterns = [
    path('', views.index, name='index'),
    path('my_languages/', views.my_languages, name='my_languages'),
    path('add_language/', views.add_language, name='add_language'),
    path('edit_language/<int:lang_id>/', views.edit_language, name='edit_language'),
    path('delete_language/', views.delete_language, name='delete_language'),
    path('edit_articles/<int:lang_id>/', views.edit_articles, name='edit_articles'), # if you change edit_articles here, make the change also in the delete_article view
    path('add_articles/<int:lang_id>/', views.add_articles, name='add_articles'),
    path('delete_article/', views.delete_article, name='delete_article'),
    path('edit_topics/<int:lang_id>/', views.edit_topics, name='edit_topics'), 
    path('add_topics/<int:lang_id>/', views.add_topics, name='add_topics'),
    path('delete_topic/', views.delete_topic, name='delete_topic'),
    path('add_entry/', views.add_entry, name='add_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/', views.delete_entry, name='delete_entry'),
    path('edit_translations/<int:entry_id>', views.edit_translations, name='edit_translations'),
    path('delete_translation/', views.delete_translation, name='delete_translation'),
    path('add_translation/<int:entry_id>', views.add_translation, name='add_translation'),
    
]

urlpatterns += staticfiles_urlpatterns()

entries/forms.py
from django import forms
from .models import Language, Article, Entry, Topic, Translation
from django.utils.translation import gettext_lazy as _

class AddLanguageForm(forms.ModelForm):
  name = forms.CharField(widget=forms.TextInput(
    attrs={'placeholder': _('language'), 'title': _('name of the language'), 'autocomplete': 'off', 'autofocus': 'on'}))
  abbreviation = forms.CharField(widget=forms.TextInput(
    attrs={'placeholder': _('abbreviation (max 4 chars)'), 'title': _('abbreviation')}))

  class Meta:
    model = Language
    fields = ['name', 'abbreviation',]

class EditArticlesForm(forms.ModelForm):
  name = forms.CharField(widget=forms.TextInput(
    attrs={'placeholder': _('article'), 'required': 'true', 'maxlength': '5'}
  ))

  class Meta:
    model = Article
    fields = ['name']

class EditTopicForm(forms.ModelForm):

  name = forms.CharField(widget=forms.TextInput(
    attrs={'required': 'true', 'placeholder': _('topic name')}
  ))

  class Meta:
    model = Article
    fields = ['name']

class EntryForm(forms.ModelForm):

  name = forms.CharField(widget=forms.TextInput(
    attrs={'required': 'true', 'placeholder': _('new word'), 'autofocus': 'on'}
  ))

  commentary = forms.CharField(
    required=False,
    widget=forms.Textarea(
      attrs={'placeholder': _('commentary'), 'cols': '17', 'rows': '1'}
    )
  )

  class Meta:
    model = Entry
    fields = ['name', 'commentary']

class TranslationForm(forms.ModelForm):

  content = forms.CharField(
    required=True,
    widget=forms.TextInput(
      attrs={'placeholder': _('translation*'), 'required': 'true'}
    )
  )

  note = forms.CharField(
    required=False,
    widget=forms.Textarea(
      attrs={'placeholder': _('translation note'), 'cols': '17', 'rows': '1'}
    )
  )

  class Meta:
    model = Translation
    fields = ['content', 'note']

entries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory
from django.db import IntegrityError
from .models import Entry, Language, Translation, Article, Topic
from .forms import AddLanguageForm, EditArticlesForm, EditTopicForm, EntryForm, TranslationForm
from .helpers import sanitize_string_input
from django.utils.translation import gettext_lazy as _

@login_required
def index(request):
  if request.user.profile.translate_by_home_lang:
    return get_translations(request)
  return get_entries(request)

@login_required
def get_entries(request):
  entries = Entry.objects.filter(
    user=request.user,
    language=request.user.profile.current_language,
  )
  context = {
    'entries': entries,
  }
  return render(request, 'entries/get_entries.html', context)

@login_required
def get_translations(request):
  translations = Translation.objects.filter(
    user=request.user,
    language=request.user.profile.current_language,
  )
  context = {
    'translations': translations,
  }
  return render(request, 'entries/get_translations.html', context)

@login_required
def my_languages(request):

  languages_query = Language.objects.filter(user=request.user)
  languages = []
  for language in languages_query:
    current_language = {
      'language': language,
      'entries': len(language.entries.all()),
      'translations': len(language.translations.all()),
      'topics': len(language.topics.all())
    }
    languages.append(current_language)

  context = {
    'languages': languages
  }

  return render(request, 'entries/languages.html', context)

@login_required
def add_language(request):

  duplicit = False
  abbreviation = ''

  if request.method == 'POST':
    form = AddLanguageForm(request.POST)

    if form.is_valid():

      abbreviation_caps = request.POST.get('abbreviation').upper()
  
      if Language.objects.filter(
        user=request.user, abbreviation=abbreviation_caps
      ):
        duplicit = True
        abbreviation = request.POST.get('abbreviation')

      else:

        # save the new language
        new_language = form.save(commit=False)
        new_language.user = request.user
        new_language.abbreviation = abbreviation_caps
        new_language.save()

        # process and save the articles, default zero article first
        Article.objects.create(user=request.user, language=new_language, name='')
        articles_set = sanitize_string_input(request.POST.get('articles'))
        for article in articles_set:
          Article.objects.create(user=request.user, language=new_language, name=article)

        # set this language as user's current_language
        request.user.profile.current_language = new_language
        request.user.profile.save()

        return edit_language(request, new_language.id)

  else:
    form = AddLanguageForm()

  context = {
    'form': form, 
    'duplicit': duplicit, 
    'abbreviation': abbreviation
  }
  return render(request, 'entries/add_language.html', context)

@login_required
def edit_language(request, lang_id):
  
  language = get_object_or_404(Language, pk=lang_id)
  duplicit = False
  abbreviation = ''

  if request.method == 'POST':
    form = AddLanguageForm(request.POST, instance=language)

    if form.is_valid():
      abbreviation_caps = request.POST.get('abbreviation').upper()

      if Language.objects.filter(
        user=request.user, 
        abbreviation=abbreviation_caps,
      ).exclude(pk=language.id):
        duplicit = True
        abbreviation = abbreviation_caps

      else:
        edited_language = form.save(commit=False)
        edited_language.abbreviation = abbreviation_caps
        edited_language.save()

        request.method = 'GET'
        return edit_language(request, lang_id)

    else:
      language = get_object_or_404(Language, pk=lang_id)

  else:
    form = AddLanguageForm(instance=language)

  context = {
    'language': language,
    'form': form,
    'duplicit': duplicit, 
    'abbreviation': abbreviation, # don't use language.abbreviation,
    'articles': language.articles.all()[1:], # to exclude the zero article
  }

  return render(request, 'entries/edit_language.html', context)

@login_required
def delete_language(request):
  language = get_object_or_404(
    Language,
    user=request.user,
    pk=request.POST.get('id')
  )

  if Language.objects.filter(user=request.user).exclude(pk=language.id).exists():
    if language == request.user.profile.current_language: 
      request.user.profile.current_language = Language.objects.filter(user=request.user).exclude(pk=language.id)[0]
  else:
    request.user.profile.current_language = None

  language.delete()
  request.user.profile.save()  

  return HttpResponse(status=204)

@login_required
def edit_articles(request, lang_id):

  articles = []
  language = get_object_or_404(Language, pk=lang_id, user=request.user)
  integrity_error = ''

  if request.method == 'GET':
    articles = language.articles.all().exclude(name='')
    ArticlesFormSet = modelformset_factory(Article, form=EditArticlesForm, extra=0)
    formset = ArticlesFormSet(queryset=articles)

  else:
    ArticlesFormSet = modelformset_factory(Article, form=EditArticlesForm, extra=0)
    formset = ArticlesFormSet(request.POST)

    if formset.is_valid():
      try:
        formset.save()
        request.method = 'GET' # before directing
        return edit_articles(request, lang_id)
      except IntegrityError:
        integrity_error = _('Each article must be unique. Please avoid duplicates.')
        # re-query the instances so the duplicate user input is replaced with the real value from the db
        articles = language.articles.all().exclude(name='')
        formset = ArticlesFormSet(queryset=articles)

    request.method = 'GET' # before directing to edit_language
    
  context = {
    'formset': formset,
    'articles_length': len(articles),
    'lang_id': lang_id,
    'lang_name': language.name,
    'integrity_error': integrity_error,
  }

  return render(request, 'entries/edit_articles.html', context)

@login_required
def add_articles(request, lang_id):
  assert request.method == 'POST'

  language = get_object_or_404(Language, pk=lang_id)
  articles_set = sanitize_string_input(request.POST.get('articles'))
  for article in articles_set:
    if not Article.objects.filter(
      user=request.user,
      language=language,
      name=article,
    ).exists() and len(article) <= 5:
      Article.objects.create(
        user=request.user,
        language=language,
        name=article,
      )

  request.method = 'GET'
  return edit_articles(request, lang_id)

@login_required
def delete_article(request):
  assert request.method == 'POST'

  article = get_object_or_404(
    Article,
    user=request.user,
    pk=request.POST.get('id'),
  )

  # entries using this article will be assigned with the zero article instead of setting Null value
  language = get_object_or_404(Language, pk=article.language.id)
  zero_article = Article.objects.filter(language=language).first()
  entries = Entry.objects.filter(user=request.user,article=article)
  for entry in entries:
    entry.article = zero_article
    entry.save()
  
  article.delete()

  return HttpResponse(status=204)

@login_required
def edit_topics(request, lang_id):

  topics = []
  language = get_object_or_404(Language, pk=lang_id)
  integrity_error = ''

  if request.method == 'GET':
    topics = Topic.objects.filter(user=request.user, language=language)
    TopicsFormSet = modelformset_factory(Topic, form=EditTopicForm, extra=0)
    formset = TopicsFormSet(queryset=topics)

  else:
    TopicsFormSet = modelformset_factory(Topic, form=EditTopicForm, extra=0)
    formset = TopicsFormSet(request.POST)

    if formset.is_valid():
      # formset.is_valid checks on the correct form inputs, then try checks the UniqueConstraint
      try:
        formset.save()
        request.method = 'GET' # before directing to edit_language
        return edit_topics(request, lang_id)
      except IntegrityError:
        integrity_error = _('Each topic must be unique. Please avoid duplicates.')
        # re-query the instances so the duplicate user input is replaced with the real value from the db
        topics = Topic.objects.filter(user=request.user, language=language)
        formset = TopicsFormSet(queryset=topics)

    request.method = 'GET' # before directing to edit_language
    
  context = {
    'formset': formset,
    'topics_length': len(topics),
    'lang_id': lang_id,
    'lang_name': language.name,
    'integrity_error': integrity_error,
  }

  return render(request, 'entries/edit_topics.html', context)

@login_required
def add_topics(request, lang_id):
  assert request.method == 'POST'

  language = get_object_or_404(Language, pk=lang_id)
  topics_set = sanitize_string_input(request.POST.get('topics'))
  for topic in topics_set:
    Topic.objects.create(
      user=request.user,
      language=language,
      name=topic,
    )

  request.method = 'GET'
  return edit_topics(request, lang_id)

@login_required
def delete_topic(request):
  assert request.method == 'POST'

  topic = get_object_or_404(
    Topic,
    user=request.user,
    pk=request.POST.get('id'),
  )
  topic.delete()

  return HttpResponse(status=204)

@login_required
def edit_entry(request, entry_id):
  entry = get_object_or_404(Entry, pk=entry_id, user=request.user)
  translations = []
  entry_integrity_error = ''
  
  if request.method == 'POST':
    # edit the entry itself
    try:
      entry_form = EntryForm(request.POST, instance=entry)
      if entry_form.is_valid():
        edited_entry = entry_form.save(commit=False)
        edited_entry.article = get_object_or_404(Article, pk=request.POST.get('article'), user=request.user)
        if request.POST.get('topic'):

entries/templates/entries/add_entry.html
{% extends 'entries/entries_index.html' %}
{% load static i18n %}

{% block content %}

<div class="text-center pb-0">
  <a href="{% url 'entries:edit_language' user.profile.current_language.id %}">
    {{ user.profile.current_language.name }}
  </a>
</div>

<h3 class="text-center" title="change language">{% trans 'add entry' %} | 
  <a href="{% url 'accounts:toggle_current_language' next_view='add_entry' %}" class="a-lang">
    {{ user.profile.current_language.abbreviation }}
  </a>
</h3>

<form action="{% url 'entries:add_entry' %}" method="POST" class="site-form">
  {% csrf_token %}
  
  {% if articles.1 %}
  <select required name="article" id="" class="custom-select">
    {% for article in articles %}
    <option class="article-option" value="{{ article.id }}">{{ article.name }}</option>
    {% endfor %}
  </select>
  {% else %}
  <input type="hidden" name="article" value="{{ articles.0.id }}">
  {% endif %}
  
  {{ entry_form.name }}
  {% if entry_form.errors.name %}
  <div class="alert alert-danger">{{ entry_form.errors.name }}</div>
  {% endif %}

  {{ entry_form.commentary }}
  {% if entry_form.errors.commentary %}
  <div class="alert alert-danger">{{ entry_form.errors.commentary }}</div>
  {% endif %}

  {% if topics %}
  <select name="topic" id="" class="custom-select">
    <option value="">{% trans '(no topic)' %}</option>
    {% for topic in topics %}
    <option value="{{ topic.id }}">{{ topic.name }}</option>
    {% endfor %}
  </select>
  {% endif %}

  {% if integrity_error_entry %}
  <div class="alert alert-danger pt-0">
    {{ integrity_error_entry }} {{ integrity_error_message }}
  </div>
  {% endif %}

  <div class="mt-3">
    {{ translation_form.content }}
    {% if translation_form.errors.content %}
    <div class="alert alert-danger">{{ translation_form.errors.content }}</div>
    {% endif %}
  
    {{ translation_form.note }}
    {% if translation_form.errors.note %}
    <div class="alert alert-danger">{{ translation_form.errors.note }}</div>
    {% endif %}
  
    <div class="text-justify">*{% trans 'only one translation. If you want to add more meanings, check the box below before saving.' %}</div>
    <input type="checkbox" value="1" name="go-to-edit" id="go-to-edit" />
    <label for="go-to-edit">{% trans 'add more translations after saving' %}</label>
  </div>

  <button type="submit" class="btn btn-outline-info btn-block mt-3">{% trans 'add entry' %}</button>
</form> 

<div class="text-justify mt-3">
  {% if articles.1 %}
  <p><b>{% trans 'Article' %}</b>: {% trans 'the article that goes with the new word' %}. 
    <a href="{% url 'entries:edit_articles' user.profile.current_language.id %}">
      {% trans 'Edit articles' %}
    </a>
  </p>
  {% endif %}
  <p><b>{% trans 'New word' %}</b>: {% trans 'the word itself' %}.</p>
  <p><b>{% trans 'Commentary' %}</b>: {% trans 'your commentary on the new word. E.g. irregularities, contextual meaning, grammatical info, trivia' %}.</p>
  {% if topics %}
  <p><b>{% trans 'Topic' %}</b>: {% trans 'only one topic per word. Useful for precise search in the dictionary' %}.
    <a href="{% url 'entries:edit_topics' user.profile.current_language.id %}">
      {% trans 'Edit topics' %}
    </a>
  </p>
  {% endif %}
  <p><b>{% trans 'Translation' %}</b>: {% trans 'save each translation one by one, so you can search for the foreign word by <i>any</i> of them' %}.</p>
  <p><b>{% trans 'Translation note' %}</b>: {% trans 'your commentary on the particular translation' %}.</p>
</div>


{% endblock %}

entries/templates/entries/edit_articles.html
{% extends 'entries/entries_index.html' %}
{% load static i18n %}
{% block content %}

<div class="text-center">
  <a href="{% url 'entries:edit_language' lang_id %}" class="text-center mb-0">{{ lang_name }}</a>
</div>

<form action="{% url 'entries:add_articles' lang_id %}" method="POST" class="site-form">
  {% csrf_token %}
  <h3 class="text-center">{% trans 'add articles' %}</h3>
  <input required type="text" class="" name="articles" placeholder="{% trans 'comma, separated, articles' %}" title="{% trans 'comma-separated articles (e.g. a, an, the)' %}">
  <div class="text-justify">*{% trans "new articles separated by a comma. E.g. 'el, la, los, las'. Note that max length of one article is 5 characters" %}.</div>
  <button type="submit" class="btn btn-outline-info btn-block my-3">{% trans 'add articles' %}</button>
</form>

{% if articles_length %}
<hr>
<form action="{% url 'entries:edit_articles' lang_id %}" method="POST" class="site-form">
  {% csrf_token %}
  {{ formset.management_form }}
  <h3 class="text-center">{% trans 'edit articles' %}</h3>

  {% for form in formset %}
  {{ form.id }}
  <div class="d-flex justify-content-between align-item-center mt-3">
    <div class="pr-2">{{ form.name }}</div>
    <button 
      type="button"  
      class="delete delete-article btn btn-outline-danger button-naked btn-block button-short"
      data-id="{{ form.id.value }}"
      data-url="{% url 'entries:delete_article' %}"
      data-name="{{ form.name.value }}"
      data-redirect="{% url 'entries:edit_articles' lang_id %}"
      data-model="article"
      ><i data-feather="x"></i>
    </button>
  </div>

  {% if form.errors %}
  <div class="alert alert-danger pt-0">{{ form.errors.name }}</div>
  {% endif %}

  {% endfor %}

  {% if integrity_error %}
  <div class="alert alert-danger mt-3">{{ integrity_error }}</div>
  {% endif %}

  <button type="submit" class="btn btn-outline-info btn-block mt-3">{% trans 'save all' %}</button>
</form>

<form id="get-token" hidden>
  {% csrf_token %}
</form>
{% endif %}

{% endblock %}

entries/templates/entries/edit_entry.html
{% extends 'entries/entries_index.html' %}
{% load static i18n %}

{% block content %}
<div class="text-center pb-0">
  <a href="{% url 'entries:edit_language' user.profile.current_language.id %}">
    {{ user.profile.current_language.name }}
  </a>
</div>

<h3 class="text-center">{{ entry.full_name}} | {{ entry.language.abbreviation }} </h3>

<form action="" name="edit-entry" method="POST" class="site-form">
  <!-- the form's name does nothing except for fixing a firefox problem in select.option.selected -->
  {% csrf_token %}


  {% if articles.1 %}
  <select required name="article" id="" class="custom-select">
    {% for article in articles %}
    <option class="article-option" value="{{ article.id }}"
      {% if article == entry.article %} selected="selected" {% endif %}
    >{{ article.name }}</option>;
    {% endfor %}
  </select>
  {% else %}
  <input type="hidden" name="article" value="{{ articles.0.id }}">
  {% endif %}

  {{ entry_form.name }}
  {% if entry_form.errors.name %}
  <div class="alert alert-danger">{{ entry_form.errors.name }}</div>
  {% endif %}

  {{ entry_form.commentary }}
  {% if entry_form.errors.commentary %}
  <div class="alert alert-danger">{{ entry_form.errors.commentary }}</div>
  {% endif %}

  {% if entry_integrity_error %}
  <div class="alert alert-danger pt-0">
    {{ entry_integrity_error }}
  </div>
  {% endif %}

  {% if topics %}
  <select name="topic" id="" class="custom-select">
    <option class="topic-option" value=""
    {% if not entry.topic %} selected="selected"{% endif %}
    >{% trans '(no topic)' %}</option>
    {% for topic in topics %}
    <option class="topic-option" value="{{ topic.id }}"
      {% if topic == entry.topic %} selected="selected" {% endif %}
    >{{ topic.name }}</option>;
    {% endfor %}
  </select>
  {% endif %}

  <button type="submit" class="btn btn-outline-info btn-block">{% trans 'save changes' %}</button>

</form>

<!-- translations -->
<!-- add translation -->
<form action="{% url 'entries:add_translation' entry.id %}" method="POST" class="site-form">
  <hr>
  <h3 class="text-center">{% trans 'add translation' %}</h3>
  {% csrf_token %}

  {{ translation_form.content }}
  {% if translation_form.errors.content %}
  <div class="alert alert-danger pt-0">{{ translation_form.errors.content }}</div>
  {% endif %}

  {{ translation_form.note }}
  {% if translation_form.errors.note %}
  <div class="alert alert-danger pt-0">{{ translation_form.errors.note }}</div>
  {% endif %}

  {% if translation_form.non_field_errors %}
  <div class="alert alert-danger pt-0">{{ translation_form.non_field_errors }}</div>
  {% endif %}

  {% if translation_integrity_error %}
  <div class="alert alert-danger pt-0">{{ translation_integrity_error }}</div>
  {% endif %}


  <div class="text-justify">*{% trans 'one translation at a time' %}</div>
  <button type="submit" class="btn btn-outline-info btn-block my-3">{% trans 'add translation' %}</button>
</form>

<!-- edit translations  -->
{% if translations_bool %}
<form action="{% url 'entries:edit_translations' entry.id %}" method="POST" class="site-form">
  <hr>
  <h3 class="text-center">{% trans 'edit translations' %}</h3>
  {% csrf_token %}
  {{ translations_formset.management_form }}
  {% for form in translations_formset %}

  {{ form.id }}
  <div class="d-flex justify-content-between align-item-center mt-3">

    <div class="pr-2">
      {{ form.content }}
      {% if form.errors.content %}
      <div class="alert alert-danger pt-0">{{ form.errors.content }}</div>
      {% endif %}  
    </div>
    
    <button 
      type="button"  
      class="delete delete-translation btn btn-outline-danger button-naked btn-block button-short"
      data-id="{{ form.id.value }}"
      data-url="{% url 'entries:delete_translation' %}"
      data-name="{{ form.content.value }}"
      data-redirect="{% url 'entries:edit_entry' entry.id %}"
      data-model="translation"
      ><i data-feather="x"></i>
    </button>

  </div>

  <div>
    {{ form.note }}
    {% if form.errors.note %}
    <div class="alert alert-danger pt-0">{{ form.errors.note }}</div>
    {% endif %}   
  </div>

  {% if form.non_field_errors %}
  <div class="alert alert-danger pt-0">{{ form.non_field_errors }}</div>
  {% endif %}

  {% endfor %}

  {% if translation_edit_integrity_error %}
  <div class="alert alert-danger pt-0">{{ translation_edit_integrity_error }}</div>
  {% endif %}
  
  <button type="submit" class="btn btn-outline-info btn-block mt-3">{% trans 'save all translations' %}</button>

  <hr>
</form>
{% endif %}

<button 
  type="button" 
  class="delete site-form delete-entry btn btn-outline-danger btn-block mt-3"
  data-name="{{ entry.name }}"
  data-id="{{ entry.id }}"
  data-url="{% url 'entries:delete_entry' %}"
  data-redirect="{% url 'entries:index' %}"
  data-model="entry"
  ><b>{% trans 'delete' %}</b> {{ entry.full_name }}
</button>

<form id="get-token" hidden>
  {% csrf_token %}
</form>

{% endblock %}

entries/templates/entries/edit_language.html
{% extends 'entries/entries_index.html' %}
{% load static i18n %}
{% block content %}
<h3 class="text-center">{{ language.name }} 
  <span class="text-uppercase">| {{ language.abbreviation }}</span> 
</h3>
  <form action="{% url 'entries:edit_language' language.id %}" method="POST" class="site-form col-6">
    {% csrf_token %} 

    {{ form.name }}
    {% if form.errors.name %}
    <div class="alert alert-danger">{{ form.errors.name }}</div>
    {% endif %}

    {{ form.abbreviation }}
    {% if form.errors.abbreviation %}
    <div class="alert alert-danger">{{ form.errors.abbreviation }}</div>
    {% endif %}

    <button type="submit" class="btn btn-outline-info btn-block mt-1">{% trans '<b>save</b> changes' %}</button>

    {% if articles %}
    <div class="mt-3 text-justify">
      <b>{% trans 'articles' %}:</b>
      {% for article in articles %}
        {{ article.name }},
      {% endfor %}
    </div>
    {% endif %}

    <div>
      <a href="{% url 'entries:edit_articles' language.id %}" class="btn btn-outline-info btn block mt-1">
        {% if articles %}
        {% trans 'edit <b>articles</b>' %}
        {% else %}
        {% trans 'add <b>articles</b>' %}
        {% endif %}
      </a>
    </div>

    {% if language.topics.all %}
    <div class="mt-3 text-justify">
      <b>{% trans 'topics' %}:</b>
      {% for topic in language.topics.all %}
        {{ topic.name }},
      {% endfor %}
    </div>
    {% endif %}

    <div>
      <a href="{% url 'entries:edit_topics' language.id %}" class="btn btn-outline-info btn block mt-1">
        {% if language.topics.all %}
        {% trans 'edit <b>topics</b>' %}
        {% else %}
        {% trans 'add <b>topics</b>' %}
        {% endif %}
      </a>
    </div>

    <div>
      <!-- <a href="{% url 'entries:add_entry' %}" class="btn btn-outline-info btn block mt-1"> -->
      <a href="{% url 'accounts:set_current_language' language.id %}" class="btn btn-outline-info btn block mt-1">
        {% trans 'add <b>new words</b>' %}
      </a>
    </div>

    <button 
      type="button" 
      class="delete delete-language btn btn-outline-danger btn-block mt-3"
      data-name="{{ language.name }}"
      data-id="{{ language.id }}"
      data-url="{% url 'entries:delete_language' %}"
      data-redirect="{% url 'entries:my_languages' %}"
      data-model="language"
      ><b>{% trans 'delete' %}</b> {{ language.name }}
    </button>

    {% if form.non_field_errors %}
    <div class="alert alert-danger">
    {{ form.non_field_errors }}
    </div>
    {% endif %}

    {% if duplicit %}
    <div class="alert alert-danger">
      {% trans 'Abbreviation' %} '{{ abbreviation }}' {% trans 'is already used by another language' %}.
    </div>
    {% endif %}

  </form>

<form id="get-token" hidden>
  {% csrf_token %}
</form>

{% endblock %}